"""
exercise.csv から LaTeX 向けスニペット（データ概要・サンプル行）を生成する。
出力: latex/data_overview_snippet.tex, latex/data_sample_table.tex
（標準ライブラリのみ）
"""
from __future__ import annotations

import csv
import pathlib
from statistics import mean

ROOT = pathlib.Path(__file__).resolve().parents[1]
CSV_PATH = ROOT / "exercise.csv"
OUT_OVERVIEW = ROOT / "latex" / "data_overview_snippet.tex"
OUT_SAMPLE = ROOT / "latex" / "data_sample_table.tex"


def tex_escape(s: str) -> str:
    return (
        str(s)
        .replace("\\", "\\textbackslash{}")
        .replace("&", "\\&")
        .replace("%", "\\%")
        .replace("#", "\\#")
        .replace("_", "\\_")
        .replace("{", "\\{")
        .replace("}", "\\}")
        .replace("~", "\\textasciitilde{}")
        .replace("^", "\\textasciicircum{}")
    )


def read_rows():
    with CSV_PATH.open(encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f))


def main() -> None:
    rows = read_rows()
    n = len(rows)
    conv = [int(r["conversion"]) for r in rows]
    cvr = mean(conv)

    def fnum(x):
        return float(x)

    # 代表行: 購入あり2, なし2, history最大1, recency最小1
    pos = [r for r in rows if r["conversion"] == "1"][:2]
    neg = [r for r in rows if r["conversion"] == "0"][:2]
    hi_hist = max(rows, key=lambda r: fnum(r["history"]))
    lo_rec = min(rows, key=lambda r: fnum(r["recency"]))
    seen = set()
    sample = []
    for r in pos + neg + [hi_hist, lo_rec]:
        key = tuple(r[c] for c in r)
        if key not in seen:
            seen.add(key)
            sample.append(r)
    sample = sample[:8]

    lines_overview = [
        r"% auto-generated by scripts/build_latex_data_snippets.py — do not edit by hand",
        rf"観測件数は \textbf{{{n:,}}} 行、全体CVR（\texttt{{conversion}}$=1$の割合）は \textbf{{{cvr:.4f}}} である。",
        r"主要な列は次のとおり。",
        r"\begin{itemize}",
        r"  \item \texttt{recency}：最終購入からの経過（月）。",
        r"  \item \texttt{history}：過去購入金額の proxy（\textbf{本レポートでは円建て}の連続値として解釈する）。",
        r"  \item \texttt{used\_discount}, \texttt{used\_bogo}：過去の割引・BOGO利用（0/1）。",
        r"  \item \texttt{zip\_code}：居住地域カテゴリ（Urban / Rural / \texttt{Surburban}）。\textbf{注：} \texttt{Surburban} はデータファイル上の綴りであり、意味は「郊外」相当（課題説明では Suburban と書かれることがある）。",
        r"  \item \texttt{is\_referral}：紹介流入フラグ（0/1）。",
        r"  \item \texttt{channel}：接触チャネル（Web / Phone / Multichannel）。",
        r"  \item \texttt{offer}：提示オファー（Discount / Buy One Get One / No Offer）。",
        r"  \item \texttt{conversion}：購入有無（0/1）。",
        r"\end{itemize}",
    ]
    OUT_OVERVIEW.write_text("\n".join(lines_overview) + "\n", encoding="utf-8")

    lines_tbl = [
        r"% auto-generated by scripts/build_latex_data_snippets.py",
        r"\begin{table}[htbp]",
        r"  \centering",
        r"  \small",
        r"  \caption{分析データの例（\texttt{exercise.csv} から抜粋。説明用の代表行）}",
        r"  \label{tab:data_examples}",
        r"  \resizebox{\linewidth}{!}{%",
        r"  \begin{tabular}{@{}rrrrlrlrlr@{}}",
        r"    \toprule",
        r"    recency & history & disc & bogo & zip & ref & channel & offer & conv \\",
        r"    \midrule",
    ]
    for r in sample:
        z = tex_escape(r["zip_code"])
        ch = tex_escape(r["channel"])
        of = tex_escape(r["offer"])
        lines_tbl.append(
            f"    {int(float(r['recency']))} & {fnum(r['history']):.2f} & {int(float(r['used_discount']))} & "
            f"{int(float(r['used_bogo']))} & {z} & {int(float(r['is_referral']))} & {ch} & {of} & {int(float(r['conversion']))} \\\\"
        )
    lines_tbl.extend(
        [
            r"    \bottomrule",
            r"  \end{tabular}",
            r"  }",
            r"\end{table}",
        ]
    )
    OUT_SAMPLE.write_text("\n".join(lines_tbl) + "\n", encoding="utf-8")
    print("Wrote", OUT_OVERVIEW.relative_to(ROOT), OUT_SAMPLE.relative_to(ROOT))


if __name__ == "__main__":
    main()
