"""
artifacts/profit_long.csv から処置別 p_conv と history を復元し、
コスト係数を変えた複数シナリオで最適処置を再計算する。
pipeline 再実行なしで「推奨の入れ替わり」感度を LaTeX 表に出力する。
"""
from __future__ import annotations

import csv
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PROFIT_LONG = ROOT / "artifacts" / "profit_long.csv"
OUT_TEX = ROOT / "latex" / "scenario_cost_sensitivity.tex"


def offer_mult(offer: str, r_disc: float, r_bogo: float) -> float:
    if offer == "No Offer":
        return 0.0
    if offer == "Buy One Get One":
        return r_bogo
    if offer == "Discount":
        return r_disc
    raise ValueError(offer)


def profit_for(offer: str, channel: str, p: float, h: float, scen: dict) -> float:
    co = h * offer_mult(offer, scen["r_disc"], scen["r_bogo"])
    cc = h * scen["ch"].get(channel, 0.0)
    return p * h - co - cc


def main() -> None:
    # 低コスト側から高コスト側まで幅を持たせる（既存 low/mid/high より極端な軸を追加）
    # name は内部キー（ASCII）。label は LaTeX 行用（\_ はエスケープ）
    scenarios = [
        {
            "name": "extreme_lean",
            "label": r"extreme\_lean（割引係数小）",
            "r_disc": 0.05,
            "r_bogo": 0.03,
            "ch": {"Web": 0.0, "Multichannel": 0.005, "Phone": 0.01},
        },
        {
            "name": "low_cost",
            "label": r"low\_cost（config 相当・やや控えめ）",
            "r_disc": 0.12,
            "r_bogo": 0.08,
            "ch": {"Web": 0.0, "Multichannel": 0.01, "Phone": 0.02},
        },
        {
            "name": "mid_cost",
            "label": r"mid\_cost",
            "r_disc": 0.35,
            "r_bogo": 0.22,
            "ch": {"Web": 0.0, "Multichannel": 0.02, "Phone": 0.04},
        },
        {
            "name": "high_cost",
            "label": r"high\_cost",
            "r_disc": 0.65,
            "r_bogo": 0.45,
            "ch": {"Web": 0.0, "Multichannel": 0.035, "Phone": 0.07},
        },
        {
            "name": "extreme_heavy",
            "label": r"extreme\_heavy（割引係数大）",
            "r_disc": 1.1,
            "r_bogo": 0.75,
            "ch": {"Web": 0.0, "Multichannel": 0.05, "Phone": 0.10},
        },
    ]

    p_map: dict[tuple[str, str], float] = {}
    h_map: dict[str, float] = {}
    treatments: set[str] = set()

    with PROFIT_LONG.open(encoding="utf-8", newline="") as f:
        for row in csv.DictReader(f):
            if row["scenario"] != "low_cost":
                continue
            cid = row["customer_id"]
            t = row["treatment"]
            treatments.add(t)
            p_map[(cid, t)] = float(row["p_conv"])
            ev = float(row["expected_value"])
            pc = float(row["p_conv"]) or 1e-12
            h_map[cid] = ev / pc

    cids = sorted(h_map.keys(), key=int)
    treat_list = sorted(treatments)

    best_by_scen: dict[str, dict[str, str]] = {}
    for scen in scenarios:
        bd: dict[str, str] = {}
        for cid in cids:
            h = h_map[cid]
            best_t = None
            best_pr = float("-inf")
            for t in treat_list:
                offer, ch = t.split(" | ")
                p = p_map[(cid, t)]
                pr = profit_for(offer, ch, p, h, scen)
                if pr > best_pr:
                    best_pr = pr
                    best_t = t
            bd[cid] = best_t or ""
        best_by_scen[scen["name"]] = bd

    # 最頻処置と割合
    mode_lines = []
    for scen in scenarios:
        cnt = Counter(best_by_scen[scen["name"]].values())
        top, ntop = cnt.most_common(1)[0]
        top_tex = top.replace(" | ", " / ")
        mode_lines.append((scen["label"], top_tex, ntop / len(cids)))

    # ペア一致率（極端同士）
    def agree(a: str, b: str) -> float:
        ba, bb = best_by_scen[a], best_by_scen[b]
        same = sum(1 for c in cids if ba[c] == bb[c])
        return same / len(cids)

    a1, a2 = scenarios[0]["name"], scenarios[-1]["name"]
    rate = agree(a1, a2)
    a1_tex = a1.replace("_", r"\_")
    a2_tex = a2.replace("_", r"\_")

    lines = [
        r"% auto-generated by scripts/build_cost_sensitivity_from_profit_long.py",
        r"\begin{table}[htbp]",
        r"  \centering",
        r"  \small",
        r"  \caption{コストシナリオ別の最頻推奨処置（\texttt{profit\_long.csv} の $p$・\texttt{history} を固定し、係数のみ変更して再計算。参考）}",
        r"  \label{tab:cost_sensitivity_modes}",
        r"  \begin{tabular}{@{}p{0.42\linewidth}p{0.48\linewidth}r@{}}",
        r"    \toprule",
        r"    シナリオ（概略） & 最頻推奨（処置） & 割合 \\",
        r"    \midrule",
    ]
    for lab, top_str, share in mode_lines:
        pct = f"{100.0 * share:.1f}\\%"
        esc = top_str.replace("_", r"\_")
        lines.append(f"    {lab} & \\texttt{{{esc}}} & {pct} \\\\")
    lines.extend(
        [
            r"    \bottomrule",
            r"  \end{tabular}",
            r"\medskip",
            rf"  \par\noindent\footnotesize 極端設定間（\texttt{{{a1_tex}}} vs \texttt{{{a2_tex}}}）で\textbf{{同一の離散処置}}が選ばれた顧客の割合：\textbf{{{100.0 * rate:.1f}\%}}（残りは処置が不一致＝コスト仮定で結論が入れ替わる）。",
            r"\end{table}",
        ]
    )
    OUT_TEX.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("Wrote", OUT_TEX.relative_to(ROOT), "n=", len(cids), "extreme agree", f"{rate:.4f}")


if __name__ == "__main__":
    main()
